spring:
  application:
    name: greeting-service
#https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    web:
      exposure:
        include:
        - "health"
greeting-service:
  greeting: "Ol√°"
  default-value: "Mundo CLOUD DEV"